(use-package polymode)
(use-package poly-markdown)
(add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))
(add-to-list 'auto-mode-alist '("\\.markdown" . poly-markdown-mode))
(add-to-list 'auto-mode-alist '("\\.md.erb" . poly-markdown-mode))
(use-package ess)
(use-package poly-R)
(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))
(add-to-list 'auto-mode-alist '("\\.Rmd.erb" . poly-markdown+r-mode))
